version: '3'
services:
    app:
        build:
            context: .
        image: "${{ secrets.DOCKER_USERNAME }}/store-springboot-app:latest"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/store
            SPRING_DATASOURCE_USERNAME: admin
            SPRING_DATASOURCE_PASSWORD: admin
        depends_on:
            - db
        ports:
            - "8080:8080"

    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: store
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - "5433:5432"
